# Ruff configuration that matches your work setup
# This replaces Black, isort, and flake8!

# Same as Black's 120 line length
line-length = 120

# Target Python 3.8+ (adjust if needed)
target-version = "py38"

[lint]
# Enable flake8 rules (E, F, W) plus isort (I)
select = ["E", "F", "W", "I"]

# Ignore the same rules as your work .flake8
ignore = [
    "E203",  # Whitespace before ':' (Black compatibility)
    "E501",  # Line too long (Ruff format handles this)
]

[format]
# Use the same formatting as Black
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[lint.isort]
# Match isort settings
combine-as-imports = true
force-wrap-aliases = true
